#!/bin/bash
# Title      : verify_certs
# Description: Mail about expiring certificates
# Author     : linuxitux
# Date       : 08-07-2015
# Usage      : ./verify_certs
# Notes      : Edit mailto, days and certs
# Notes      : Add this to your crontab on a weekly basis
#10 1 * * 1 root /root/scripts/verify_certs >> /var/log/verify_certs.log 2>&1

MAILTO="dvader@linuxito.com"
MAILER="/usr/bin/mail"
#MAILER='/root/scripts/mailgun-mta.sh --text -r "Linuxito <root@linuxito.com>"'

DAYS=10
CERTS="/usr/local/nginx/conf/*.crt /usr/local/apache/conf/ssl.crt/*.crt /etc/letsencrypt/live/example.com/cert.pem"

SERVER=$(hostname)
SUBJECT="Warning: SSL certificates about to expire in $SERVER"
MAIL=""

echo "[$(date)]"

for FILE in $CERTS
do
  EXP=$(/usr/bin/openssl x509 -enddate -noout -in $FILE)
  EXP=${EXP:9}
  EXPD=$(date --date="$EXP" +%d-%m-%Y)
  echo $FILE expira el $EXPD
  EXP=$(date --date="$EXP" +%Y%m%d)

  for (( i=0; i<=$DAYS; i++ ))
  do
    DATE=$(date --date="+$i days" +%Y%m%d)
    if [ "$EXP" = "$DATE" ]; then
      if [ "$i" = "0" ]; then MAIL=$(echo -e "$FILE expires today!\n$MAIL")
      else MAIL=$(echo -e "$FILE expires in $i day(s).\n$MAIL")
      fi
    fi
  done

done

if [ "${#MAIL}" -gt 0 ]; then
  # enviar notificación
  MAIL=$(echo -e "Status of SSL certificates:\n$MAIL\n")
  echo -e "$MAIL" | $MAILER -s "$SUBJECT" $MAILTO
  echo -e "$MAIL"
else
  echo "Status of SSL certicates: OK."
fi
