#!/bin/csh
# Title      : update
# Description: Full FreeBSD update from sources
# Author     : linuxitux
# Date       : 06-08-2015
# Usage      : ./update
# Notes      : https://www.freebsd.org/doc/handbook/updating-upgrading.html

echo "Updating world and generic kernel..."
echo "===================================="
freebsd-update fetch && freebsd-update install

echo "Updating ports from sources..."
echo "=============================="
portsnap fetch && portsnap update && portmaster -aD

echo "Checking dependencies..."
echo "========================"
portmaster --check-depends && portmaster --check-port-dbdir

echo "Cleaning unused packages..."
echo "==========================="
portmaster -y --clean-distfiles && portmaster -y --clean-packages && portmaster -y -s

echo "Checking known vulnerabilities..."
echo "================================="
pkg audit -F
