#!/bin/csh
# Title      : freebsd_update
# Description: FreeBSD update
# Author     : linuxitux
# Date       : 07-07-2015
# Usage      : ./freebsd_update
# Notes      : https://www.freebsd.org/doc/handbook/updating-upgrading.html

echo "Current version: "
freebsd-version
uname -a
echo

echo "Checking updates..."
freebsd-update fetch && freebsd-update install
